### ISSUE TITLE
classifyByStandard OSError: Empty or corrupt FITS file

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#115]
sp = splat.getSpectrum(lucky=True)

Retrieving 1 lucky file

splat.classifyByStandard(sp)
Traceback (most recent call last):

  File "<ipython-input-43-181f51b884c4>", line 1, in <module>
    splat.classifyByStandard(sp)

  File "/Users/daniella/Python/splat/splat/core.py", line 4543, in classifyByStandard
    initiateStandards()

  File "/Users/daniella/Python/splat/splat/core.py", line 2984, in initiateStandards
    stds[t] = Spectrum(kys[t])

  File "/Users/daniella/Python/splat/splat/core.py", line 253, in __init__
    rs = readSpectrum(self.filename,**mkwargs)

  File "/Users/daniella/Python/splat/splat/core.py", line 3766, in readSpectrum
    with fits.open(os.path.normpath(file),ignore_missing_end=True) as data:

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1032, in _readfrom
    raise IOError('Empty or corrupt FITS file')

OSError: Empty or corrupt FITS file

**Comment by daniellabardalezgagliuffi** [comment]
seems to be a problem with the field standards:

splat.classifyByStandard(sp,vlg=True)
Out[69]: ('M7.0gamma', 0.5)

splat.classifyByStandard(sp,vlg=True,plot=True)
Out[70]: ('M7.0gamma', 0.5)

splat.classifyByStandard(sp,fldg=True,plot=True)
Traceback (most recent call last):

  File "<ipython-input-71-d923e09c854c>", line 1, in <module>
    splat.classifyByStandard(sp,fldg=True,plot=True)

  File "/Users/daniella/Python/splat/splat/core.py", line 4543, in classifyByStandard
    initiateStandards()

  File "/Users/daniella/Python/splat/splat/core.py", line 2984, in initiateStandards
    stds[t] = Spectrum(kys[t])

  File "/Users/daniella/Python/splat/splat/core.py", line 253, in __init__
    rs = readSpectrum(self.filename,**mkwargs)

  File "/Users/daniella/Python/splat/splat/core.py", line 3766, in readSpectrum
    with fits.open(os.path.normpath(file),ignore_missing_end=True) as data:

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1032, in _readfrom
    raise IOError('Empty or corrupt FITS file')

OSError: Empty or corrupt FITS file

**Comment by aburgasser** [comment]
Tracked down to a corrupt file on the local machine - if this issue comes up, solution is to update the contents of splat/code/splat/Reference/Spectra
