### ISSUE TITLE
classifyByIndex method not working

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#123]
b,be = splat.classifyByIndex(sp,set='Burgasser')

Traceback (most recent call last):

  File "<ipython-input-13-f59c76bc601d>", line 1, in <module>
    b,be = splat.classifyByIndex(sp,set='Burgasser')

  File "/Users/daniella/Python/splat/splat/core.py", line 4261, in classifyByIndex
    indices = measureIndexSet(sp, **kwargs)

  File "/Users/daniella/Python/splat/splat/core.py", line 5945, in measureIndexSet
    ind,err = measureIndex(sp,*ranges[i],method=methods[i],sample=samples[i],**kwargs)

TypeError: measureIndex() got multiple values for argument 'method'

**Comment by aburgasser** [comment]
sorry, this is turning into a surprisingly deep bug, still working on it

**Comment by aburgasser** [comment]
OK, that was a deep one but is now up and running; let me know if the error comes back
