### ISSUE TITLE
simulateAges finds index out of range on "protective offset"

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#128]
age = np.array(simulate.simulateAges(10000, distribution='uniform'))
Traceback (most recent call last):

  File "<ipython-input-17-9f7fd38be2d6>", line 1, in <module>
    age = np.array(simulate.simulateAges(10000, distribution='uniform'))

  File "/Users/daniella/Python/splat/splat/simulate.py", line 309, in simulateAges
    if age_range[0] == age_range[1]:

IndexError: list index out of range

**Comment by aburgasser** [comment]
fixed
